import Head from 'next/head';
import Button from '../components/Button';

export default function Home() {
	return (
		<div className='flex flex-col min-h-screen bg-gray-900 items-center justify-center'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Button />
			</main>
		</div>
	);
}
